FROM php:7.1.3-fpm

MAINTAINER Jackson Tong <tongtoan2704@gmail.com>
WORKDIR /var/www/

RUN apt-get update \
  && apt-get install -y --no-install-recommends zlib1g-dev libicu-dev g++ \
      libfreetype6-dev \
      libjpeg62-turbo-dev \
      libssl-dev \
      libmcrypt-dev \
      libpng12-dev \
      libmagickwand-dev \
      git \
  && docker-php-ext-install -j$(nproc) iconv mcrypt \
  && docker-php-ext-configure gd --enable-gd-native-ttf --with-jpeg-dir=/usr/lib/x86_64-linux-gnu --with-png-dir=/usr/lib/x86_64-linux-gnu --with-freetype-dir=/usr/lib/x86_64-linux-gnu \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl \
  && docker-php-ext-install zip \
  && docker-php-ext-install pdo_mysql \
  && docker-php-ext-install -j$(nproc) gd \
  && pecl install imagick \
  && docker-php-ext-enable imagick \
  # install mongodb driver
  && pecl install mongodb-1.3.0 \
  && docker-php-ext-enable mongodb \
  && rm -rf /var/lib/apt/lists/*

#install composer
COPY install-composer.sh /var/www
RUN /var/www/install-composer.sh