version: '2'
services:
  application:
    image: busybox:latest
    volumes:
      - $PWD:/var/www
  nginx:
    build: docker/nginx
    ports:
      - "9090:80"
      - "443:443"
    volumes_from:
      - application
    depends_on:
      - php-fpm
  php-fpm:
    build: docker/php
    volumes_from:
      - application
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
  mysql:
    build: docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}