version: '2'
services:
  application:
    image: busybox:latest
    volumes:
      - $PWD:/var/www
  nginx:
    build: docker/nginx
    ports:
      - "9090:80"
    volumes_from:
      - application
    depends_on:
      - php-fpm
  php-fpm:
    build: docker/php
    volumes_from:
      - application